<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOclJRnI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOclJRnI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOclJRnI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOclJRnI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOclJRnI\App_KernelDevDebugContainer([
    'container.build_hash' => 'OclJRnI',
    'container.build_id' => 'ffca2aab',
    'container.build_time' => 1747514405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOclJRnI');
