<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'api_cards_list' => [[], ['_controller' => 'App\\Controller\\Api\\CardController::list'], [], [['text', '/api/cards']], [], [], []],
    'game_attack' => [['sectorId', 'diceRoll'], ['_controller' => 'App\\Controller\\Api\\CardController::attack'], [], [['variable', '/', '[^/]++', 'diceRoll', true], ['variable', '/', '[^/]++', 'sectorId', true], ['text', '/api/attack']], [], [], []],
    'attack_sector' => [['sector', 'diceScore'], ['_controller' => 'App\\Controller\\GameController::attackSector'], [], [['variable', '/', '[^/]++', 'diceScore', true], ['variable', '/', '[^/]++', 'sector', true], ['text', '/api/attack']], [], [], []],
    'draw_event' => [[], ['_controller' => 'App\\Controller\\GameController::drawEvent'], [], [['text', '/api/draw-event']], [], [], []],
    'api_home' => [[], ['_controller' => 'App\\Controller\\Api\\RootController::home'], [], [['text', '/']], [], [], []],
    'api_sectors_list' => [[], ['_controller' => 'App\\Controller\\Api\\SectorController::list'], [], [['text', '/api/sectors']], [], [], []],
    'api_sector_show' => [['id'], ['_controller' => 'App\\Controller\\Api\\SectorController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/sectors']], [], [], []],
    'get_attaque' => [['id'], ['_controller' => 'App\\Controller\\AttaqueController::getAttaque'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/attaque']], [], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/api/register']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/api/login']], [], [], []],
    'test_attaque' => [['id'], ['_controller' => 'App\\Controller\\TestController::testAttaque'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/test/attaque']], [], [], []],
    'start-game' => [[], ['_controller' => 'App\\Controller\\Api\\CardController::startGame'], [], [['text', '/api/start-game']], [], [], []],
    'api_start_game' => [[], ['_controller' => 'App\\Controller\\Api\\CardController::startGame'], [], [['text', '/api/start-game']], [], [], []],
];
