<?php

namespace ContainerOclJRnI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QJvd3GHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QJvd3GH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QJvd3GH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sectorRepository' => ['privates', 'App\\Repository\\SectorRepository', 'getSectorRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', true],
        ], [
            'sectorRepository' => 'App\\Repository\\SectorRepository',
            'serializer' => '?',
        ]);
    }
}
