<?php

namespace ContainerOclJRnI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EUuF6eaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eUuF6ea' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eUuF6ea'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cardRepository' => ['privates', 'App\\Repository\\CardRepository', 'getCardRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', true],
        ], [
            'cardRepository' => 'App\\Repository\\CardRepository',
            'serializer' => '?',
        ]);
    }
}
