<?php

namespace ContainerOclJRnI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AwKp_NYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AwKp.nY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AwKp.nY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cardRepository' => ['privates', 'App\\Repository\\CardRepository', 'getCardRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sectorRepository' => ['privates', 'App\\Repository\\SectorRepository', 'getSectorRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', true],
        ], [
            'cardRepository' => 'App\\Repository\\CardRepository',
            'entityManager' => '?',
            'sectorRepository' => 'App\\Repository\\SectorRepository',
            'serializer' => '?',
        ]);
    }
}
