<?php

namespace ContainerOclJRnI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ITEykoZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ITEykoZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ITEykoZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Api\\CardController::attack' => ['privates', '.service_locator.AwKp.nY', 'get_ServiceLocator_AwKp_NYService', true],
            'App\\Controller\\Api\\CardController::list' => ['privates', '.service_locator.eUuF6ea', 'get_ServiceLocator_EUuF6eaService', true],
            'App\\Controller\\Api\\CardController::startGame' => ['privates', '.service_locator.8Q_2ICh', 'get_ServiceLocator_8Q2IChService', true],
            'App\\Controller\\Api\\SectorController::list' => ['privates', '.service_locator.QJvd3GH', 'get_ServiceLocator_QJvd3GHService', true],
            'App\\Controller\\Api\\SectorController::show' => ['privates', '.service_locator.QJvd3GH', 'get_ServiceLocator_QJvd3GHService', true],
            'App\\Controller\\AttaqueController::getAttaque' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.mK6IRPJ', 'get_ServiceLocator_MK6IRPJService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\Api\\CardController:attack' => ['privates', '.service_locator.AwKp.nY', 'get_ServiceLocator_AwKp_NYService', true],
            'App\\Controller\\Api\\CardController:list' => ['privates', '.service_locator.eUuF6ea', 'get_ServiceLocator_EUuF6eaService', true],
            'App\\Controller\\Api\\CardController:startGame' => ['privates', '.service_locator.8Q_2ICh', 'get_ServiceLocator_8Q2IChService', true],
            'App\\Controller\\Api\\SectorController:list' => ['privates', '.service_locator.QJvd3GH', 'get_ServiceLocator_QJvd3GHService', true],
            'App\\Controller\\Api\\SectorController:show' => ['privates', '.service_locator.QJvd3GH', 'get_ServiceLocator_QJvd3GHService', true],
            'App\\Controller\\AttaqueController:getAttaque' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.mK6IRPJ', 'get_ServiceLocator_MK6IRPJService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\Api\\CardController::attack' => '?',
            'App\\Controller\\Api\\CardController::list' => '?',
            'App\\Controller\\Api\\CardController::startGame' => '?',
            'App\\Controller\\Api\\SectorController::list' => '?',
            'App\\Controller\\Api\\SectorController::show' => '?',
            'App\\Controller\\AttaqueController::getAttaque' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Api\\CardController:attack' => '?',
            'App\\Controller\\Api\\CardController:list' => '?',
            'App\\Controller\\Api\\CardController:startGame' => '?',
            'App\\Controller\\Api\\SectorController:list' => '?',
            'App\\Controller\\Api\\SectorController:show' => '?',
            'App\\Controller\\AttaqueController:getAttaque' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
